# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Game.destroy_all





Game.create(title: "Doom Eternal: Standard Edition", genre: "First-Person Shooter", maturity_rating:"Mature", description:"The follow-up to 2016’s Doom reboot is as explosive as ever, but this isn’t just a fast-paced shooter. In addition to running and gunning, you’ll balance unique resource management mechanics that make for a super-nuanced battle against the hordes from hell.", image:"https://www.mobygames.com/images/covers/l/642689-doom-eternal-playstation-4-front-cover.png", banner:"https://images3.alphacoders.com/102/thumb-1920-1025036.jpg", video:"https://www.youtube.com/watch?v=FkklG9MA0vM")
Game.create(title: "Nioh 2", genre: "Action", maturity_rating:"Mature", description:"One-word description of Nioh 2: Wow. The follow-up to the original Nioh is a prequel to that story, but it’s that much more exciting, delivering intricate battling mechanics that can’t help but remind me of Ninja Gaiden. But then you control yourself as a Yokai, and things get even more vicious, and visceral.", image:"https://www.mobygames.com/images/covers/l/641257-nioh-2-playstation-4-front-cover.jpg", banner:"https://gameranx.com/wp-content/uploads/2018/09/Nioh-2-4K-Wallpaper.jpg", video:"https://www.youtube.com/watch?v=ETWtvVGFNqU")
Game.create(title: "Resident Evil 3", genre: "Third-Person Shooter", maturity_rating:"Mature", description:"The latest Resident Evil 3 video game remake gives a major facelift to the 1999 PlayStation 2 game, which was one of my favorite Resident Evils. Yes, Nemesis will keep reappearing in this iteration, too, adding a serious freakout factor to the entire experience. And there are some big surprises, too.", image:"https://www.mobygames.com/images/covers/l/625564-resident-evil-3-playstation-4-front-cover.png", banner:"https://images2.alphacoders.com/105/thumb-1920-1057560.jpg", video:"https://www.youtube.com/watch?v=9LrLM4Hvr9U")
Game.create(title: "Star Wars Jedi: Fallen Order", genre: "Action", maturity_rating:"Teen", description:"Learn new Jedi powers as Padawan Cal Kestis, in a story that takes place five years after Revenge of the Sith (yes, this video game is officially Star Wars canon). Star Wars fans, come because it’s canon, and because the storytelling is immersive and enjoyable. Gamers, come because those force powers play well.", image:"https://www.mobygames.com/images/covers/l/607882-star-wars-jedi-fallen-order-playstation-4-front-cover.jpg", banner:"https://wallpapercave.com/wp/wp4884525.jpg", video:"https://www.youtube.com/watch?v=0GLbwkfhYZk")
Game.create(title: "The Outer Worlds", genre: "Action", maturity_rating:"Mature", description:"A fantastic back story is the backbone of this sci-fi RPG, which casts you as a colonist who awakens from hibernation to find a strange new world before him. It has a sense of humor and plenty of varied combat, but here’s the best part of the video game: Your decisions drive the story and the development of your character in an open-ended and authentic way.", image:"https://www.mobygames.com/images/covers/l/601524-the-outer-worlds-playstation-4-front-cover.jpg", banner:"https://wallpaperaccess.com/full/1911489.jpg", video:"https://www.youtube.com/watch?v=Oxlflrh_Pzw")
Game.create(title: "Nier: Automata", genre: "Action", maturity_rating:"Mature", description:"NieR:Automata is an action role-playing video game developed by Platinum Games and published by Square Enix for the PlayStation 4 and PC. It is the indirect sequel to both NieR RepliCant and NieR Gestalt (NIER), and is set in the year 11945, during the 14th Machine War.", image:"https://www.mobygames.com/images/covers/l/382107-nier-automata-playstation-4-front-cover.jpg", banner:"https://wallpaperpure.net/wp-content/uploads/2018/07/958e16e2f9d1cc5d47b5a12b2e3314f9-1600x900.jpeg", video:"https://www.youtube.com/watch?v=wJxNhJ8fjFk")
Game.create(title: "The Witcher 3: Wild Hunt", genre: "Adventure", maturity_rating:"Mature", description:"With the Empire attacking the Kingdoms of the North and the Wild Hunt, a cavalcade of ghastly riders, breathing down your neck, the only way to survive is to fight back. As Geralt of Rivia, a master swordsman and monster hunter, leave none of your enemies standing. Explore a gigantic open world, slay beasts and decide the fates of whole communities with your actions, all in a genuine next generation format.", image:"https://www.mobygames.com/images/covers/l/305108-the-witcher-3-wild-hunt-playstation-4-front-cover.jpg", banner:"https://i.pinimg.com/originals/c2/49/f1/c249f14eccea62157e7e65461cb15708.jpg", video:"https://www.youtube.com/watch?v=c0i88t0Kacs")
Game.create(title: "MLB The Show 20", genre: "Sports", maturity_rating:"Everyone", description:"Real baseball is on pause, so it’s a good thing that the best baseball video game out there continues to deliver. The latest iteration of MLB: The Show is also more loaded than ever, thanks to full minor league rosters (translation: Franchise mode finally feels realistic) and ultra-strong on-field gameplay.", image:"https://www.mobygames.com/images/covers/l/642071-mlb-the-show-20-playstation-4-front-cover.png", banner:"https://wallpapercave.com/wp/wp5281400.jpg", video:"https://www.youtube.com/watch?v=BKOn0NZ7Tpc")
Game.create(title: "Borderlands 3", genre: "First-Person Shooter", maturity_rating:"Mature", description:"The legendary shooter-looter returns with its third main entry, and this one is as explosive as they come, featuring a story that calls back to the first two titles, and enough guns, side quests, and battles to keep you busy for hours on end. ", image:"https://www.mobygames.com/images/covers/l/590809-borderlands-3-playstation-4-front-cover.png", banner:"https://wallpaperaccess.com/full/1270506.jpg", video:"https://www.youtube.com/watch?v=d9Gu1PspA3Y")
Game.create(title: "Animal Crossing: New Horizons", genre: "Adventure", maturity_rating:"Everyone", description:"The only rule in Animal Crossing: New Horizon video game is really this: There are no rules. You wake up on an island, quickly find a house, then start paying bills. It’s a wildly chill, wildly relaxing experience that simulates all the best parts of tropical island life in Nintendo’s trademark cartoon-driven way.", image:"https://www.mobygames.com/images/covers/l/632236-animal-crossing-new-horizons-nintendo-switch-front-cover.jpg", banner:"https://nintendowire.com/wp-content/uploads/2020/03/Banner-AnimalCrossing-NewHorizons-Characters-Line.jpg", video:"https://www.youtube.com/watch?v=_3YNL0OWio0")
Game.create(title: "Death Stranding", genre: "Action", maturity_rating:"Mature", description:"Visionary video game director Hideo Kojima returns with perhaps his most prescient game ever in Death Stranding. It’s a post-apocalyptic movie come to life, complete with lengthy cutscenes, and a pretty foreboding snapshot of life to come: Humans live apart in tiny communities rarely interacting with each other, save the postmen who traverse the surface delivering packages from area to area. Humanity is dying thanks to a disease. Sound familiar? Eerily so.", image:"https://www.mobygames.com/images/covers/l/602285-death-stranding-playstation-4-front-cover.jpg", banner:"https://wallpaperaccess.com/full/951834.jpg", video:"https://www.youtube.com/watch?v=tCI396HyhbQ")
Game.create(title: "Pokemon Sword and Shield", genre: "Adventure", maturity_rating:"Everyone", description:"The first official Pokemon video game release on the Switch that was built just for the Switch, Pokemon Sword (or Shield, whichever you pick up) plays like a Pokemon cartoon come to life. It’s turn-based battling is at its best this go-round, and yes, it’s still as fun as ever to try to catch ‘em all!", image:"https://www.mobygames.com/images/covers/l/607726-pokemon-sword-nintendo-switch-front-cover.jpg", banner:"https://wallpapercave.com/wp/wp4565982.jpg", video:"https://www.youtube.com/watch?v=uBYORdr_TY8")
Game.create(title: "Street Fighter V Champion Edition", genre: "Fighting", maturity_rating:"Teen", description:"If you play one fighting video game in 2020, make this one it. Street Fighter V’s final iteration is loaded with content and fighters, and delivers a deep fighting system that has enough accessibility for newbies but complexity that can take experts plenty of time to master.", image:"https://www.mobygames.com/images/covers/l/450059-street-fighter-v-arcade-edition-playstation-4-front-cover.png", banner:"https://images5.alphacoders.com/559/thumb-1920-559865.jpg", video:"https://www.youtube.com/watch?v=bTVfIOS5xwQ")
Game.create(title: "Gears 5", genre: "Third-Person Shooter", maturity_rating:"Mature", description:"A new generation of protagonist arrives for Gears 5, the fifth proper release in the Gears of War franchise. This time, it’s Kait Diaz leading the way in a title that features some underrated storytelling, and plenty of the cover-shooter gameplay you’ve come to know and love.", image:"https://www.mobygames.com/images/covers/l/589166-gears-5-windows-apps-front-cover.jpg", banner:"https://cdn.gearsofwar.com/gearsforums/original/2X/f/f24e79151d385e7120f791cd2da799bd18ae2065.jpg", video:"https://www.youtube.com/watch?v=SEpWlFfpEkU")
Game.create(title: "Ori and the Will of The Wisps", genre: "Platform", maturity_rating:"Everyone", description:"Go old-school video gaming with Ori and the Will of the Wisps, a Metroidvania-style game that has you platforming and gradually learning new abilities. The difference: There’s a distinct vibe of fairy-tale and wonderment here, and you’ll come to love the endearing star, the adopted guardian Ori.", image:"https://www.mobygames.com/images/covers/l/684529-ori-and-the-will-of-the-wisps-nintendo-switch-front-cover.jpg", banner:"https://msgpwebcdn.azureedge.net/ori/wp-content/uploads/2017/06/WotW_wallpaperGraveyard_2560x1440.jpg", video:"https://www.youtube.com/watch?v=2reK8k8nwBc")
Game.create(title: "Madden NFL 20", genre: "Sports", maturity_rating:"Everyone", description:"Last year’s Madden had some early bugs, but once those were steadied, the game took off. Now, it plays like a dream, with the new Superstar X-Factors delivering game-changing moments that make football’s very best finally play a cut above everyone else", image:"https://www.mobygames.com/images/covers/l/593288-madden-nfl-20-playstation-4-front-cover.jpg", banner:"https://wallpapercave.com/wp/wp4519220.jpg", video:"https://www.youtube.com/watch?v=oHOudL5d14M")
Game.create(title: "Luigi's Mansion 3", genre: "Adventure", maturity_rating:"Everyone", description:"Mario’s fraidy-cat brother returns for another lighthearted creep-fest through a dark mansion, and this time he has new puzzle-solving powers. It’s as fun a jaunt through a ghost house as you may ever have.", image:"https://www.mobygames.com/images/covers/l/603143-luigi-s-mansion-3-nintendo-switch-front-cover.jpg", banner:"https://twinfinite.net/wp-content/uploads/2019/10/luigis-mansion-wallpaper-3-1.jpg", video:"https://www.youtube.com/watch?v=RSGgCfbYrg0")
Game.create(title: "Wolfenstein: Youngblood", genre: "First-Person Shooter", maturity_rating:"Mature", description:"The Wolfenstein video game series has never been quite this off-the-rails. But that’s not a bad thing. This wild ride is built for cooperative campaigning and features open-ended gameplay, guns that have serious pop, and wildly fast-paced action.", image:"https://www.mobygames.com/images/covers/l/579200-wolfenstein-youngblood-playstation-4-front-cover.jpg", banner:"https://cdn.wallpapersafari.com/76/48/0duhkc.jpg", video:"https://www.youtube.com/watch?v=SNpgKytPcc4")
Game.create(title: "Darksiders Genesis", genre: "Action", maturity_rating:"Teen", description:"Here’s a seriously underrated video game. Darksiders Genesis takes the look and feel of Diablo and adds a bit more snarky, self-aware demon story and a generous helping of cooperative play, keeping you busy with a friend for hours on end.", image:"https://www.mobygames.com/images/covers/l/616087-darksiders-genesis-playstation-4-front-cover.jpg", banner:"https://hdwallsource.com/img/2019/6/darksiders-genesis-game-wallpaper-69728-72092-hd-wallpapers.jpg", video:"https://www.youtube.com/watch?v=M_BkKeHoTi0")
Game.create(title: "Super Mario Maker 2", genre: "Platform", maturity_rating:"Everyone", description:"The only thing better than all those levels of Super Mario you played as a kid? An infinite amount of Super Mario levels. That’s what you get with Super Mario Maker 2, which delivers an easy-to-use toolkit that can let you build your own levels. I was never any good at that, but here’s the best part: You can try out other people’s levels, too, meaning plenty of spins on the uniqueness and excitement of the original Mario.", image:"https://www.mobygames.com/images/covers/l/540073-super-mario-maker-2-nintendo-switch-front-cover.jpg", banner:"https://wallpaperaccess.com/full/1896673.png", video:"https://www.youtube.com/watch?v=CYx9v7Mo94M")
Game.create(title: "NBA 2K20", genre: "Sports", maturity_rating:"Everyone", description:"The best basketball video game in town keeps doing what it does (even though a bit less talk of in-game virtual currency would rock). On the court, the game looks better than ever, and franchise mode continues to set the bar for all sports games. If you’re a hoops fan, this is a must-play now that the NBA itself is on pause.", image:"https://www.mobygames.com/images/covers/l/589053-nba-2k20-playstation-4-front-cover.jpg", banner:"https://images.wallpapersden.com/image/download/nba-2k20-cover_a2ptbm2UmZqaraWkpJRmbmdlrWZlbWU.jpg", video:"https://www.youtube.com/watch?v=FQ7WBnSvjIo")
Game.create(title: "DRAGON BALL Z: Kakarot", genre: "Action", maturity_rating:"Teen", description:"Can a Dragon Ball Z video game be fun if it’s not a fighting game? Yes. Bandai Namco makes sure of that with Kakarot, a unique take on the DBZ series that plays out like a role-playing game in a semi-open world. ", image:"https://www.mobygames.com/images/covers/l/625731-dragon-ball-z-kakarot-playstation-4-front-cover.jpg", banner:"https://wallpapercave.com/wp/wp5563154.jpg", video:"https://www.youtube.com/watch?v=Bf85wwJuFBE")



# A user must have a UserGame instance to review a game
# Review.create(user_id: User.first.id, game_id: Game.first.id, rating: 2.3, content: '3sdadasda')

# UserGame means the game was added to your game list as a played game, no review, not favorited by default
# UserGame.create(user_id: User.first.id, game_id: Game.second.id, favorite: false)


